import type { Word } from '@/entities/word/model/types';

/**
 * JLPT N3 핵심 단어장 — 빈출 & 필수 단어 모음
 * 카테고리: 일상, 학업, 업무, 감정, 시간, 장소, 자연, 관계, 건강, 표현 등
 *
 * 이 데이터는 supabase/seed.sql 로 변환되어 원격 DB에 적재됩니다.
 * `npm run seed:supabase` 로 동기화할 수 있습니다 (scripts/seed-supabase.mjs 참고).
 */
export const SEED_WORDS: Word[] = [
  // ==================== 동사 (일상/행동) ====================
  {
    id: 1,
    kanji: '決める',
    reading: 'きめる',
    meaning_ko: '결정하다, 정하다',
    part_of_speech: 'verb',
    category: '일상',
    frequency_rank: 1,
    is_essential: true,
    examples: [
      {
        sentence_jp: '来週の予定をもう決めましたか。',
        sentence_ko: '다음 주 일정을 이미 정하셨나요?',
      },
    ],
  },
  {
    id: 2,
    kanji: '集める',
    reading: 'あつめる',
    meaning_ko: '모으다, 수집하다',
    part_of_speech: 'verb',
    category: '일상',
    frequency_rank: 2,
    is_essential: true,
    examples: [
      {
        sentence_jp: '子供の頃から切手を集めています。',
        sentence_ko: '어릴 때부터 우표를 모으고 있어요.',
      },
    ],
  },
  {
    id: 3,
    kanji: '比べる',
    reading: 'くらべる',
    meaning_ko: '비교하다',
    part_of_speech: 'verb',
    category: '사고',
    frequency_rank: 3,
    is_essential: true,
    examples: [
      {
        sentence_jp: '去年と比べて、今年はとても忙しい。',
        sentence_ko: '작년과 비교해서 올해는 정말 바쁘다.',
      },
    ],
  },
  {
    id: 4,
    kanji: '続ける',
    reading: 'つづける',
    meaning_ko: '계속하다',
    part_of_speech: 'verb',
    category: '일상',
    frequency_rank: 4,
    is_essential: true,
    examples: [
      {
        sentence_jp: '毎日少しずつ勉強を続けている。',
        sentence_ko: '매일 조금씩 공부를 계속하고 있다.',
      },
    ],
  },
  {
    id: 5,
    kanji: '進める',
    reading: 'すすめる',
    meaning_ko: '진행하다, 나아가게 하다',
    part_of_speech: 'verb',
    category: '업무',
    frequency_rank: 5,
    is_essential: true,
    examples: [
      {
        sentence_jp: 'プロジェクトを計画通りに進めた。',
        sentence_ko: '프로젝트를 계획대로 진행했다.',
      },
    ],
  },
  {
    id: 6,
    kanji: '伝える',
    reading: 'つたえる',
    meaning_ko: '전하다, 알리다',
    part_of_speech: 'verb',
    category: '관계',
    frequency_rank: 6,
    is_essential: true,
    examples: [
      {
        sentence_jp: '母によろしくとお伝えください。',
        sentence_ko: '어머니께 안부 전해 주세요.',
      },
    ],
  },
  {
    id: 7,
    kanji: '迎える',
    reading: 'むかえる',
    meaning_ko: '맞이하다, 마중하다',
    part_of_speech: 'verb',
    category: '관계',
    frequency_rank: 7,
    is_essential: true,
    examples: [
      {
        sentence_jp: '駅まで友達を迎えに行く。',
        sentence_ko: '역까지 친구를 마중하러 간다.',
      },
    ],
  },
  {
    id: 8,
    kanji: '守る',
    reading: 'まもる',
    meaning_ko: '지키다, 보호하다',
    part_of_speech: 'verb',
    category: '사회',
    frequency_rank: 8,
    is_essential: true,
    examples: [
      {
        sentence_jp: '約束は必ず守ります。',
        sentence_ko: '약속은 반드시 지킵니다.',
      },
    ],
  },
  {
    id: 9,
    kanji: '育てる',
    reading: 'そだてる',
    meaning_ko: '키우다, 기르다',
    part_of_speech: 'verb',
    category: '관계',
    frequency_rank: 9,
    is_essential: true,
    examples: [
      {
        sentence_jp: '庭でトマトを育てている。',
        sentence_ko: '마당에서 토마토를 키우고 있다.',
      },
    ],
  },
  {
    id: 10,
    kanji: '選ぶ',
    reading: 'えらぶ',
    meaning_ko: '고르다, 선택하다',
    part_of_speech: 'verb',
    category: '일상',
    frequency_rank: 10,
    is_essential: true,
    examples: [
      {
        sentence_jp: '好きな色を自由に選んでください。',
        sentence_ko: '좋아하는 색을 자유롭게 골라 주세요.',
      },
    ],
  },
  {
    id: 11,
    kanji: '断る',
    reading: 'ことわる',
    meaning_ko: '거절하다',
    part_of_speech: 'verb',
    category: '관계',
    frequency_rank: 11,
    is_essential: true,
    examples: [
      {
        sentence_jp: 'その仕事は丁寧に断った。',
        sentence_ko: '그 일은 정중하게 거절했다.',
      },
    ],
  },
  {
    id: 12,
    kanji: '預かる',
    reading: 'あずかる',
    meaning_ko: '맡다, 보관하다',
    part_of_speech: 'verb',
    category: '일상',
    frequency_rank: 12,
    is_essential: false,
    examples: [
      {
        sentence_jp: '荷物をしばらく預かってもらえますか。',
        sentence_ko: '짐을 잠시 맡아 주시겠어요?',
      },
    ],
  },
  {
    id: 13,
    kanji: '預ける',
    reading: 'あずける',
    meaning_ko: '맡기다',
    part_of_speech: 'verb',
    category: '일상',
    frequency_rank: 13,
    is_essential: false,
    examples: [
      {
        sentence_jp: '銀行にお金を預けた。',
        sentence_ko: '은행에 돈을 맡겼다.',
      },
    ],
  },
  {
    id: 14,
    kanji: '泊まる',
    reading: 'とまる',
    meaning_ko: '묵다, 숙박하다',
    part_of_speech: 'verb',
    category: '여행',
    frequency_rank: 14,
    is_essential: true,
    examples: [
      {
        sentence_jp: '昨日はホテルに泊まった。',
        sentence_ko: '어제는 호텔에 묵었다.',
      },
    ],
  },
  {
    id: 15,
    kanji: '手伝う',
    reading: 'てつだう',
    meaning_ko: '돕다, 거들다',
    part_of_speech: 'verb',
    category: '관계',
    frequency_rank: 15,
    is_essential: true,
    examples: [
      {
        sentence_jp: '母の料理を手伝った。',
        sentence_ko: '엄마의 요리를 도왔다.',
      },
    ],
  },
  {
    id: 16,
    kanji: '急ぐ',
    reading: 'いそぐ',
    meaning_ko: '서두르다',
    part_of_speech: 'verb',
    category: '일상',
    frequency_rank: 16,
    is_essential: true,
    examples: [
      {
        sentence_jp: '時間がないので急ぎましょう。',
        sentence_ko: '시간이 없으니 서두릅시다.',
      },
    ],
  },
  {
    id: 17,
    kanji: '驚く',
    reading: 'おどろく',
    meaning_ko: '놀라다',
    part_of_speech: 'verb',
    category: '감정',
    frequency_rank: 17,
    is_essential: true,
    examples: [
      {
        sentence_jp: '突然のニュースに驚いた。',
        sentence_ko: '갑작스러운 뉴스에 놀랐다.',
      },
    ],
  },
  {
    id: 18,
    kanji: '探す',
    reading: 'さがす',
    meaning_ko: '찾다',
    part_of_speech: 'verb',
    category: '일상',
    frequency_rank: 18,
    is_essential: true,
    examples: [
      {
        sentence_jp: '鍵をずっと探している。',
        sentence_ko: '열쇠를 계속 찾고 있다.',
      },
    ],
  },
  {
    id: 19,
    kanji: '間違える',
    reading: 'まちがえる',
    meaning_ko: '틀리다, 잘못하다',
    part_of_speech: 'verb',
    category: '학업',
    frequency_rank: 19,
    is_essential: true,
    examples: [
      {
        sentence_jp: '名前の漢字を間違えてしまった。',
        sentence_ko: '이름의 한자를 틀려 버렸다.',
      },
    ],
  },
  {
    id: 20,
    kanji: '覚える',
    reading: 'おぼえる',
    meaning_ko: '외우다, 기억하다',
    part_of_speech: 'verb',
    category: '학업',
    frequency_rank: 20,
    is_essential: true,
    examples: [
      {
        sentence_jp: '新しい単語を百個覚えた。',
        sentence_ko: '새로운 단어를 백 개 외웠다.',
      },
    ],
  },
  {
    id: 21,
    kanji: '慣れる',
    reading: 'なれる',
    meaning_ko: '익숙해지다',
    part_of_speech: 'verb',
    category: '일상',
    frequency_rank: 21,
    is_essential: true,
    examples: [
      {
        sentence_jp: '東京の生活にもう慣れました。',
        sentence_ko: '도쿄 생활에 이미 익숙해졌어요.',
      },
    ],
  },
  {
    id: 22,
    kanji: '困る',
    reading: 'こまる',
    meaning_ko: '곤란하다, 난처하다',
    part_of_speech: 'verb',
    category: '감정',
    frequency_rank: 22,
    is_essential: true,
    examples: [
      {
        sentence_jp: '道が分からなくて困っています。',
        sentence_ko: '길을 몰라서 곤란해하고 있어요.',
      },
    ],
  },
  {
    id: 23,
    kanji: '誘う',
    reading: 'さそう',
    meaning_ko: '권하다, 초대하다',
    part_of_speech: 'verb',
    category: '관계',
    frequency_rank: 23,
    is_essential: true,
    examples: [
      {
        sentence_jp: '友達を映画に誘った。',
        sentence_ko: '친구를 영화에 초대했다.',
      },
    ],
  },
  {
    id: 24,
    kanji: '比べる',
    reading: 'くらべる',
    meaning_ko: '비교하다',
    part_of_speech: 'verb',
    category: '사고',
    frequency_rank: 24,
    is_essential: false,
    examples: [
      {
        sentence_jp: '価格を比べてから買うのがいい。',
        sentence_ko: '가격을 비교한 뒤에 사는 게 좋다.',
      },
    ],
  },
  {
    id: 25,
    kanji: '間に合う',
    reading: 'まにあう',
    meaning_ko: '시간에 맞추다, 늦지 않다',
    part_of_speech: 'verb',
    category: '시간',
    frequency_rank: 25,
    is_essential: true,
    examples: [
      {
        sentence_jp: '走ればまだ電車に間に合う。',
        sentence_ko: '뛰면 아직 전철을 놓치지 않는다.',
      },
    ],
  },
  {
    id: 26,
    kanji: '遅れる',
    reading: 'おくれる',
    meaning_ko: '늦다, 지각하다',
    part_of_speech: 'verb',
    category: '시간',
    frequency_rank: 26,
    is_essential: true,
    examples: [
      {
        sentence_jp: '電車が事故で遅れている。',
        sentence_ko: '전철이 사고로 지연되고 있다.',
      },
    ],
  },
  {
    id: 27,
    kanji: '過ぎる',
    reading: 'すぎる',
    meaning_ko: '지나다, 넘다',
    part_of_speech: 'verb',
    category: '시간',
    frequency_rank: 27,
    is_essential: true,
    examples: [
      {
        sentence_jp: 'もう夜の十時を過ぎた。',
        sentence_ko: '벌써 밤 10시를 넘겼다.',
      },
    ],
  },
  {
    id: 28,
    kanji: '別れる',
    reading: 'わかれる',
    meaning_ko: '헤어지다',
    part_of_speech: 'verb',
    category: '관계',
    frequency_rank: 28,
    is_essential: true,
    examples: [
      {
        sentence_jp: '駅の前で友達と別れた。',
        sentence_ko: '역 앞에서 친구와 헤어졌다.',
      },
    ],
  },
  {
    id: 29,
    kanji: '笑う',
    reading: 'わらう',
    meaning_ko: '웃다',
    part_of_speech: 'verb',
    category: '감정',
    frequency_rank: 29,
    is_essential: true,
    examples: [
      {
        sentence_jp: '彼の冗談にみんな笑った。',
        sentence_ko: '그의 농담에 모두 웃었다.',
      },
    ],
  },
  {
    id: 30,
    kanji: '泣く',
    reading: 'なく',
    meaning_ko: '울다',
    part_of_speech: 'verb',
    category: '감정',
    frequency_rank: 30,
    is_essential: true,
    examples: [
      {
        sentence_jp: '子供が大きな声で泣いている。',
        sentence_ko: '아이가 큰 소리로 울고 있다.',
      },
    ],
  },
  {
    id: 31,
    kanji: '残る',
    reading: 'のこる',
    meaning_ko: '남다',
    part_of_speech: 'verb',
    category: '일상',
    frequency_rank: 31,
    is_essential: true,
    examples: [
      {
        sentence_jp: 'お弁当が少し残った。',
        sentence_ko: '도시락이 조금 남았다.',
      },
    ],
  },
  {
    id: 32,
    kanji: '残す',
    reading: 'のこす',
    meaning_ko: '남기다',
    part_of_speech: 'verb',
    category: '일상',
    frequency_rank: 32,
    is_essential: false,
    examples: [
      {
        sentence_jp: '料理を残さずに食べた。',
        sentence_ko: '음식을 남기지 않고 먹었다.',
      },
    ],
  },
  {
    id: 33,
    kanji: '増える',
    reading: 'ふえる',
    meaning_ko: '늘다, 증가하다',
    part_of_speech: 'verb',
    category: '변화',
    frequency_rank: 33,
    is_essential: true,
    examples: [
      {
        sentence_jp: '最近、外国人観光客が増えた。',
        sentence_ko: '요즘 외국인 관광객이 늘었다.',
      },
    ],
  },
  {
    id: 34,
    kanji: '減る',
    reading: 'へる',
    meaning_ko: '줄다, 감소하다',
    part_of_speech: 'verb',
    category: '변화',
    frequency_rank: 34,
    is_essential: true,
    examples: [
      {
        sentence_jp: '人口が少しずつ減っている。',
        sentence_ko: '인구가 조금씩 줄고 있다.',
      },
    ],
  },
  {
    id: 35,
    kanji: '変わる',
    reading: 'かわる',
    meaning_ko: '바뀌다, 변하다',
    part_of_speech: 'verb',
    category: '변화',
    frequency_rank: 35,
    is_essential: true,
    examples: [
      {
        sentence_jp: 'この町は十年で大きく変わった。',
        sentence_ko: '이 마을은 10년 사이에 크게 변했다.',
      },
    ],
  },
  {
    id: 36,
    kanji: '変える',
    reading: 'かえる',
    meaning_ko: '바꾸다',
    part_of_speech: 'verb',
    category: '변화',
    frequency_rank: 36,
    is_essential: true,
    examples: [
      {
        sentence_jp: '会議の日を来週に変えた。',
        sentence_ko: '회의 날짜를 다음 주로 바꿨다.',
      },
    ],
  },
  {
    id: 37,
    kanji: '進む',
    reading: 'すすむ',
    meaning_ko: '나아가다, 진행되다',
    part_of_speech: 'verb',
    category: '업무',
    frequency_rank: 37,
    is_essential: true,
    examples: [
      {
        sentence_jp: '工事がなかなか進まない。',
        sentence_ko: '공사가 좀처럼 진행되지 않는다.',
      },
    ],
  },
  {
    id: 38,
    kanji: '離れる',
    reading: 'はなれる',
    meaning_ko: '떨어지다, 멀어지다',
    part_of_speech: 'verb',
    category: '관계',
    frequency_rank: 38,
    is_essential: true,
    examples: [
      {
        sentence_jp: '家族と離れて暮らしている。',
        sentence_ko: '가족과 떨어져 살고 있다.',
      },
    ],
  },
  {
    id: 39,
    kanji: '届く',
    reading: 'とどく',
    meaning_ko: '도착하다, 닿다',
    part_of_speech: 'verb',
    category: '일상',
    frequency_rank: 39,
    is_essential: true,
    examples: [
      {
        sentence_jp: '注文した本が今朝届いた。',
        sentence_ko: '주문한 책이 오늘 아침 도착했다.',
      },
    ],
  },
  {
    id: 40,
    kanji: '届ける',
    reading: 'とどける',
    meaning_ko: '전달하다, 갖다 주다',
    part_of_speech: 'verb',
    category: '일상',
    frequency_rank: 40,
    is_essential: false,
    examples: [
      {
        sentence_jp: '忘れ物を交番に届けた。',
        sentence_ko: '분실물을 파출소에 가져다 주었다.',
      },
    ],
  },
  {
    id: 41,
    kanji: '済む',
    reading: 'すむ',
    meaning_ko: '끝나다, 해결되다',
    part_of_speech: 'verb',
    category: '업무',
    frequency_rank: 41,
    is_essential: true,
    examples: [
      {
        sentence_jp: '仕事がやっと済んだ。',
        sentence_ko: '일이 드디어 끝났다.',
      },
    ],
  },
  {
    id: 42,
    kanji: '片付ける',
    reading: 'かたづける',
    meaning_ko: '정리하다, 치우다',
    part_of_speech: 'verb',
    category: '일상',
    frequency_rank: 42,
    is_essential: true,
    examples: [
      {
        sentence_jp: '週末に部屋を片付けた。',
        sentence_ko: '주말에 방을 정리했다.',
      },
    ],
  },
  {
    id: 43,
    kanji: '直す',
    reading: 'なおす',
    meaning_ko: '고치다, 수정하다',
    part_of_speech: 'verb',
    category: '일상',
    frequency_rank: 43,
    is_essential: true,
    examples: [
      {
        sentence_jp: '自転車を自分で直した。',
        sentence_ko: '자전거를 직접 고쳤다.',
      },
    ],
  },
  {
    id: 44,
    kanji: '治る',
    reading: 'なおる',
    meaning_ko: '(병이) 낫다',
    part_of_speech: 'verb',
    category: '건강',
    frequency_rank: 44,
    is_essential: true,
    examples: [
      {
        sentence_jp: '風邪はもう治りました。',
        sentence_ko: '감기는 이제 다 나았어요.',
      },
    ],
  },
  {
    id: 45,
    kanji: '似る',
    reading: 'にる',
    meaning_ko: '닮다',
    part_of_speech: 'verb',
    category: '관계',
    frequency_rank: 45,
    is_essential: true,
    examples: [
      {
        sentence_jp: '妹は母によく似ている。',
        sentence_ko: '여동생은 엄마를 많이 닮았다.',
      },
    ],
  },
  {
    id: 46,
    kanji: '渡る',
    reading: 'わたる',
    meaning_ko: '건너다',
    part_of_speech: 'verb',
    category: '이동',
    frequency_rank: 46,
    is_essential: true,
    examples: [
      {
        sentence_jp: '橋を渡ると駅があります。',
        sentence_ko: '다리를 건너면 역이 있습니다.',
      },
    ],
  },
  {
    id: 47,
    kanji: '渡す',
    reading: 'わたす',
    meaning_ko: '건네주다',
    part_of_speech: 'verb',
    category: '이동',
    frequency_rank: 47,
    is_essential: false,
    examples: [
      {
        sentence_jp: '手紙を直接彼に渡した。',
        sentence_ko: '편지를 직접 그에게 건네주었다.',
      },
    ],
  },
  {
    id: 48,
    kanji: '運ぶ',
    reading: 'はこぶ',
    meaning_ko: '나르다, 옮기다',
    part_of_speech: 'verb',
    category: '이동',
    frequency_rank: 48,
    is_essential: true,
    examples: [
      {
        sentence_jp: '荷物を二階に運んだ。',
        sentence_ko: '짐을 2층으로 옮겼다.',
      },
    ],
  },
  {
    id: 49,
    kanji: '貸す',
    reading: 'かす',
    meaning_ko: '빌려주다',
    part_of_speech: 'verb',
    category: '관계',
    frequency_rank: 49,
    is_essential: true,
    examples: [
      {
        sentence_jp: '友達に傘を貸した。',
        sentence_ko: '친구에게 우산을 빌려주었다.',
      },
    ],
  },
  {
    id: 50,
    kanji: '借りる',
    reading: 'かりる',
    meaning_ko: '빌리다',
    part_of_speech: 'verb',
    category: '관계',
    frequency_rank: 50,
    is_essential: true,
    examples: [
      {
        sentence_jp: '図書館で本を借りた。',
        sentence_ko: '도서관에서 책을 빌렸다.',
      },
    ],
  },

  // ==================== 명사 ====================
  {
    id: 51,
    kanji: '約束',
    reading: 'やくそく',
    meaning_ko: '약속',
    part_of_speech: 'noun',
    category: '관계',
    frequency_rank: 51,
    is_essential: true,
    examples: [
      {
        sentence_jp: '友達との約束を忘れてしまった。',
        sentence_ko: '친구와의 약속을 잊어버렸다.',
      },
    ],
  },
  {
    id: 52,
    kanji: '経験',
    reading: 'けいけん',
    meaning_ko: '경험',
    part_of_speech: 'noun',
    category: '업무',
    frequency_rank: 52,
    is_essential: true,
    examples: [
      {
        sentence_jp: '海外での仕事は貴重な経験になった。',
        sentence_ko: '해외 근무는 귀중한 경험이 되었다.',
      },
    ],
  },
  {
    id: 53,
    kanji: '連絡',
    reading: 'れんらく',
    meaning_ko: '연락',
    part_of_speech: 'noun',
    category: '관계',
    frequency_rank: 53,
    is_essential: true,
    examples: [
      {
        sentence_jp: '後で電話で連絡します。',
        sentence_ko: '나중에 전화로 연락드릴게요.',
      },
    ],
  },
  {
    id: 54,
    kanji: '確認',
    reading: 'かくにん',
    meaning_ko: '확인',
    part_of_speech: 'noun',
    category: '업무',
    frequency_rank: 54,
    is_essential: true,
    examples: [
      {
        sentence_jp: '予約の確認をお願いします。',
        sentence_ko: '예약 확인 부탁드립니다.',
      },
    ],
  },
  {
    id: 55,
    kanji: '予定',
    reading: 'よてい',
    meaning_ko: '예정, 일정',
    part_of_speech: 'noun',
    category: '시간',
    frequency_rank: 55,
    is_essential: true,
    examples: [
      {
        sentence_jp: '明日の予定を教えてください。',
        sentence_ko: '내일 일정을 알려 주세요.',
      },
    ],
  },
  {
    id: 56,
    kanji: '計画',
    reading: 'けいかく',
    meaning_ko: '계획',
    part_of_speech: 'noun',
    category: '업무',
    frequency_rank: 56,
    is_essential: true,
    examples: [
      {
        sentence_jp: '旅行の計画を立てている。',
        sentence_ko: '여행 계획을 세우고 있다.',
      },
    ],
  },
  {
    id: 57,
    kanji: '準備',
    reading: 'じゅんび',
    meaning_ko: '준비',
    part_of_speech: 'noun',
    category: '일상',
    frequency_rank: 57,
    is_essential: true,
    examples: [
      {
        sentence_jp: '試験の準備はもう終わった。',
        sentence_ko: '시험 준비는 이미 끝났다.',
      },
    ],
  },
  {
    id: 58,
    kanji: '予約',
    reading: 'よやく',
    meaning_ko: '예약',
    part_of_speech: 'noun',
    category: '일상',
    frequency_rank: 58,
    is_essential: true,
    examples: [
      {
        sentence_jp: 'レストランを予約しました。',
        sentence_ko: '레스토랑을 예약했어요.',
      },
    ],
  },
  {
    id: 59,
    kanji: '努力',
    reading: 'どりょく',
    meaning_ko: '노력',
    part_of_speech: 'noun',
    category: '학업',
    frequency_rank: 59,
    is_essential: true,
    examples: [
      {
        sentence_jp: '毎日の努力が大切です。',
        sentence_ko: '매일의 노력이 중요합니다.',
      },
    ],
  },
  {
    id: 60,
    kanji: '成功',
    reading: 'せいこう',
    meaning_ko: '성공',
    part_of_speech: 'noun',
    category: '업무',
    frequency_rank: 60,
    is_essential: true,
    examples: [
      {
        sentence_jp: '彼はついに成功した。',
        sentence_ko: '그는 마침내 성공했다.',
      },
    ],
  },
  {
    id: 61,
    kanji: '失敗',
    reading: 'しっぱい',
    meaning_ko: '실패',
    part_of_speech: 'noun',
    category: '업무',
    frequency_rank: 61,
    is_essential: true,
    examples: [
      {
        sentence_jp: '失敗から多くを学んだ。',
        sentence_ko: '실패에서 많은 것을 배웠다.',
      },
    ],
  },
  {
    id: 62,
    kanji: '文化',
    reading: 'ぶんか',
    meaning_ko: '문화',
    part_of_speech: 'noun',
    category: '사회',
    frequency_rank: 62,
    is_essential: true,
    examples: [
      {
        sentence_jp: '日本の伝統文化に興味があります。',
        sentence_ko: '일본의 전통 문화에 관심이 있어요.',
      },
    ],
  },
  {
    id: 63,
    kanji: '社会',
    reading: 'しゃかい',
    meaning_ko: '사회',
    part_of_speech: 'noun',
    category: '사회',
    frequency_rank: 63,
    is_essential: true,
    examples: [
      {
        sentence_jp: '現代社会は変化が早い。',
        sentence_ko: '현대 사회는 변화가 빠르다.',
      },
    ],
  },
  {
    id: 64,
    kanji: '経済',
    reading: 'けいざい',
    meaning_ko: '경제',
    part_of_speech: 'noun',
    category: '사회',
    frequency_rank: 64,
    is_essential: true,
    examples: [
      {
        sentence_jp: '日本の経済について勉強している。',
        sentence_ko: '일본 경제에 대해 공부하고 있다.',
      },
    ],
  },
  {
    id: 65,
    kanji: '政治',
    reading: 'せいじ',
    meaning_ko: '정치',
    part_of_speech: 'noun',
    category: '사회',
    frequency_rank: 65,
    is_essential: false,
    examples: [
      {
        sentence_jp: '政治のニュースを毎日読む。',
        sentence_ko: '정치 뉴스를 매일 읽는다.',
      },
    ],
  },
  {
    id: 66,
    kanji: '環境',
    reading: 'かんきょう',
    meaning_ko: '환경',
    part_of_speech: 'noun',
    category: '사회',
    frequency_rank: 66,
    is_essential: true,
    examples: [
      {
        sentence_jp: '環境問題について話し合った。',
        sentence_ko: '환경 문제에 대해 논의했다.',
      },
    ],
  },
  {
    id: 67,
    kanji: '情報',
    reading: 'じょうほう',
    meaning_ko: '정보',
    part_of_speech: 'noun',
    category: '사회',
    frequency_rank: 67,
    is_essential: true,
    examples: [
      {
        sentence_jp: 'インターネットで情報を集める。',
        sentence_ko: '인터넷에서 정보를 모은다.',
      },
    ],
  },
  {
    id: 68,
    kanji: '関係',
    reading: 'かんけい',
    meaning_ko: '관계',
    part_of_speech: 'noun',
    category: '관계',
    frequency_rank: 68,
    is_essential: true,
    examples: [
      {
        sentence_jp: '二人は仕事の関係で知り合った。',
        sentence_ko: '두 사람은 업무상 알게 되었다.',
      },
    ],
  },
  {
    id: 69,
    kanji: '意見',
    reading: 'いけん',
    meaning_ko: '의견',
    part_of_speech: 'noun',
    category: '사고',
    frequency_rank: 69,
    is_essential: true,
    examples: [
      {
        sentence_jp: 'あなたの意見を聞かせてください。',
        sentence_ko: '당신의 의견을 들려주세요.',
      },
    ],
  },
  {
    id: 70,
    kanji: '理由',
    reading: 'りゆう',
    meaning_ko: '이유',
    part_of_speech: 'noun',
    category: '사고',
    frequency_rank: 70,
    is_essential: true,
    examples: [
      {
        sentence_jp: '遅刻の理由を説明した。',
        sentence_ko: '지각한 이유를 설명했다.',
      },
    ],
  },
  {
    id: 71,
    kanji: '問題',
    reading: 'もんだい',
    meaning_ko: '문제',
    part_of_speech: 'noun',
    category: '학업',
    frequency_rank: 71,
    is_essential: true,
    examples: [
      {
        sentence_jp: 'この数学の問題は難しい。',
        sentence_ko: '이 수학 문제는 어렵다.',
      },
    ],
  },
  {
    id: 72,
    kanji: '解決',
    reading: 'かいけつ',
    meaning_ko: '해결',
    part_of_speech: 'noun',
    category: '사고',
    frequency_rank: 72,
    is_essential: true,
    examples: [
      {
        sentence_jp: '問題の解決に時間がかかった。',
        sentence_ko: '문제 해결에 시간이 걸렸다.',
      },
    ],
  },
  {
    id: 73,
    kanji: '理解',
    reading: 'りかい',
    meaning_ko: '이해',
    part_of_speech: 'noun',
    category: '사고',
    frequency_rank: 73,
    is_essential: true,
    examples: [
      {
        sentence_jp: '説明を聞いて理解できた。',
        sentence_ko: '설명을 듣고 이해할 수 있었다.',
      },
    ],
  },
  {
    id: 74,
    kanji: '説明',
    reading: 'せつめい',
    meaning_ko: '설명',
    part_of_speech: 'noun',
    category: '학업',
    frequency_rank: 74,
    is_essential: true,
    examples: [
      {
        sentence_jp: '先生の説明がとても分かりやすい。',
        sentence_ko: '선생님의 설명이 아주 이해하기 쉽다.',
      },
    ],
  },
  {
    id: 75,
    kanji: '質問',
    reading: 'しつもん',
    meaning_ko: '질문',
    part_of_speech: 'noun',
    category: '학업',
    frequency_rank: 75,
    is_essential: true,
    examples: [
      {
        sentence_jp: '何か質問はありますか。',
        sentence_ko: '뭔가 질문 있으신가요?',
      },
    ],
  },
  {
    id: 76,
    kanji: '意味',
    reading: 'いみ',
    meaning_ko: '의미, 뜻',
    part_of_speech: 'noun',
    category: '학업',
    frequency_rank: 76,
    is_essential: true,
    examples: [
      {
        sentence_jp: 'この言葉の意味を教えてください。',
        sentence_ko: '이 단어의 뜻을 알려 주세요.',
      },
    ],
  },
  {
    id: 77,
    kanji: '発表',
    reading: 'はっぴょう',
    meaning_ko: '발표',
    part_of_speech: 'noun',
    category: '업무',
    frequency_rank: 77,
    is_essential: true,
    examples: [
      {
        sentence_jp: '明日、研究の発表があります。',
        sentence_ko: '내일 연구 발표가 있어요.',
      },
    ],
  },
  {
    id: 78,
    kanji: '相談',
    reading: 'そうだん',
    meaning_ko: '상담, 의논',
    part_of_speech: 'noun',
    category: '관계',
    frequency_rank: 78,
    is_essential: true,
    examples: [
      {
        sentence_jp: '大事な話は両親と相談した。',
        sentence_ko: '중요한 얘기는 부모님과 의논했다.',
      },
    ],
  },
  {
    id: 79,
    kanji: '生活',
    reading: 'せいかつ',
    meaning_ko: '생활',
    part_of_speech: 'noun',
    category: '일상',
    frequency_rank: 79,
    is_essential: true,
    examples: [
      {
        sentence_jp: '一人暮らしの生活にも慣れた。',
        sentence_ko: '혼자 사는 생활에도 익숙해졌다.',
      },
    ],
  },
  {
    id: 80,
    kanji: '習慣',
    reading: 'しゅうかん',
    meaning_ko: '습관',
    part_of_speech: 'noun',
    category: '일상',
    frequency_rank: 80,
    is_essential: true,
    examples: [
      {
        sentence_jp: '毎朝ランニングをする習慣がある。',
        sentence_ko: '매일 아침 달리기 하는 습관이 있다.',
      },
    ],
  },
  {
    id: 81,
    kanji: '性格',
    reading: 'せいかく',
    meaning_ko: '성격',
    part_of_speech: 'noun',
    category: '관계',
    frequency_rank: 81,
    is_essential: true,
    examples: [
      {
        sentence_jp: '姉は明るい性格です。',
        sentence_ko: '언니는 밝은 성격이에요.',
      },
    ],
  },
  {
    id: 82,
    kanji: '気持ち',
    reading: 'きもち',
    meaning_ko: '기분, 마음',
    part_of_speech: 'noun',
    category: '감정',
    frequency_rank: 82,
    is_essential: true,
    examples: [
      {
        sentence_jp: '今日は気持ちがいい天気だ。',
        sentence_ko: '오늘은 기분 좋은 날씨다.',
      },
    ],
  },
  {
    id: 83,
    kanji: '気分',
    reading: 'きぶん',
    meaning_ko: '기분, 컨디션',
    part_of_speech: 'noun',
    category: '감정',
    frequency_rank: 83,
    is_essential: true,
    examples: [
      {
        sentence_jp: '少し気分が悪い。',
        sentence_ko: '조금 기분이 안 좋다.',
      },
    ],
  },
  {
    id: 84,
    kanji: '記憶',
    reading: 'きおく',
    meaning_ko: '기억',
    part_of_speech: 'noun',
    category: '사고',
    frequency_rank: 84,
    is_essential: false,
    examples: [
      {
        sentence_jp: '子供の頃の記憶がまだ残っている。',
        sentence_ko: '어릴 적 기억이 아직 남아 있다.',
      },
    ],
  },
  {
    id: 85,
    kanji: '最近',
    reading: 'さいきん',
    meaning_ko: '최근, 요즘',
    part_of_speech: 'noun',
    category: '시간',
    frequency_rank: 85,
    is_essential: true,
    examples: [
      {
        sentence_jp: '最近、よく雨が降る。',
        sentence_ko: '요즘 비가 자주 온다.',
      },
    ],
  },
  {
    id: 86,
    kanji: '将来',
    reading: 'しょうらい',
    meaning_ko: '장래, 미래',
    part_of_speech: 'noun',
    category: '시간',
    frequency_rank: 86,
    is_essential: true,
    examples: [
      {
        sentence_jp: '将来の夢は医者になることだ。',
        sentence_ko: '장래 꿈은 의사가 되는 것이다.',
      },
    ],
  },
  {
    id: 87,
    kanji: '機会',
    reading: 'きかい',
    meaning_ko: '기회',
    part_of_speech: 'noun',
    category: '업무',
    frequency_rank: 87,
    is_essential: true,
    examples: [
      {
        sentence_jp: '機会があればまた会いましょう。',
        sentence_ko: '기회가 되면 또 만나요.',
      },
    ],
  },
  {
    id: 88,
    kanji: '場所',
    reading: 'ばしょ',
    meaning_ko: '장소',
    part_of_speech: 'noun',
    category: '장소',
    frequency_rank: 88,
    is_essential: true,
    examples: [
      {
        sentence_jp: '会う場所を決めましょう。',
        sentence_ko: '만날 장소를 정합시다.',
      },
    ],
  },
  {
    id: 89,
    kanji: '景色',
    reading: 'けしき',
    meaning_ko: '경치, 풍경',
    part_of_speech: 'noun',
    category: '자연',
    frequency_rank: 89,
    is_essential: true,
    examples: [
      {
        sentence_jp: '山の上からの景色は最高だ。',
        sentence_ko: '산 위에서 보는 경치는 최고다.',
      },
    ],
  },
  {
    id: 90,
    kanji: '交通',
    reading: 'こうつう',
    meaning_ko: '교통',
    part_of_speech: 'noun',
    category: '사회',
    frequency_rank: 90,
    is_essential: true,
    examples: [
      {
        sentence_jp: 'この町は交通が便利だ。',
        sentence_ko: '이 도시는 교통이 편리하다.',
      },
    ],
  },
  {
    id: 91,
    kanji: '事故',
    reading: 'じこ',
    meaning_ko: '사고',
    part_of_speech: 'noun',
    category: '사회',
    frequency_rank: 91,
    is_essential: true,
    examples: [
      {
        sentence_jp: '昨日、近くで交通事故があった。',
        sentence_ko: '어제 근처에서 교통사고가 있었다.',
      },
    ],
  },
  {
    id: 92,
    kanji: '趣味',
    reading: 'しゅみ',
    meaning_ko: '취미',
    part_of_speech: 'noun',
    category: '일상',
    frequency_rank: 92,
    is_essential: true,
    examples: [
      {
        sentence_jp: '趣味は写真を撮ることです。',
        sentence_ko: '취미는 사진 찍기입니다.',
      },
    ],
  },
  {
    id: 93,
    kanji: '将来',
    reading: 'しょうらい',
    meaning_ko: '장래',
    part_of_speech: 'noun',
    category: '시간',
    frequency_rank: 93,
    is_essential: false,
    examples: [
      {
        sentence_jp: '将来のために貯金している。',
        sentence_ko: '미래를 위해 저금하고 있다.',
      },
    ],
  },
  {
    id: 94,
    kanji: '結果',
    reading: 'けっか',
    meaning_ko: '결과',
    part_of_speech: 'noun',
    category: '업무',
    frequency_rank: 94,
    is_essential: true,
    examples: [
      {
        sentence_jp: '試験の結果を待っている。',
        sentence_ko: '시험 결과를 기다리고 있다.',
      },
    ],
  },
  {
    id: 95,
    kanji: '原因',
    reading: 'げんいん',
    meaning_ko: '원인',
    part_of_speech: 'noun',
    category: '사고',
    frequency_rank: 95,
    is_essential: true,
    examples: [
      {
        sentence_jp: '事故の原因を調査している。',
        sentence_ko: '사고의 원인을 조사하고 있다.',
      },
    ],
  },
  {
    id: 96,
    kanji: '目的',
    reading: 'もくてき',
    meaning_ko: '목적',
    part_of_speech: 'noun',
    category: '업무',
    frequency_rank: 96,
    is_essential: true,
    examples: [
      {
        sentence_jp: '旅行の目的は何ですか。',
        sentence_ko: '여행의 목적은 무엇입니까?',
      },
    ],
  },
  {
    id: 97,
    kanji: '方法',
    reading: 'ほうほう',
    meaning_ko: '방법',
    part_of_speech: 'noun',
    category: '사고',
    frequency_rank: 97,
    is_essential: true,
    examples: [
      {
        sentence_jp: 'もっといい方法がないか考えた。',
        sentence_ko: '더 좋은 방법이 없는지 생각했다.',
      },
    ],
  },
  {
    id: 98,
    kanji: '世界',
    reading: 'せかい',
    meaning_ko: '세계',
    part_of_speech: 'noun',
    category: '사회',
    frequency_rank: 98,
    is_essential: true,
    examples: [
      {
        sentence_jp: '世界中を旅行したい。',
        sentence_ko: '세계를 여행하고 싶다.',
      },
    ],
  },
  {
    id: 99,
    kanji: '自然',
    reading: 'しぜん',
    meaning_ko: '자연',
    part_of_speech: 'noun',
    category: '자연',
    frequency_rank: 99,
    is_essential: true,
    examples: [
      {
        sentence_jp: '自然の中で散歩するのが好きだ。',
        sentence_ko: '자연 속에서 산책하는 걸 좋아한다.',
      },
    ],
  },
  {
    id: 100,
    kanji: '気候',
    reading: 'きこう',
    meaning_ko: '기후',
    part_of_speech: 'noun',
    category: '자연',
    frequency_rank: 100,
    is_essential: false,
    examples: [
      {
        sentence_jp: 'ここは気候が温暖だ。',
        sentence_ko: '이곳은 기후가 온난하다.',
      },
    ],
  },

  // ==================== 형용사 ====================
  {
    id: 101,
    kanji: '複雑',
    reading: 'ふくざつ',
    meaning_ko: '복잡함',
    part_of_speech: 'na-adjective',
    category: '사고',
    frequency_rank: 101,
    is_essential: true,
    examples: [
      {
        sentence_jp: 'この問題はとても複雑だ。',
        sentence_ko: '이 문제는 매우 복잡하다.',
      },
    ],
  },
  {
    id: 102,
    kanji: '単純',
    reading: 'たんじゅん',
    meaning_ko: '단순함',
    part_of_speech: 'na-adjective',
    category: '사고',
    frequency_rank: 102,
    is_essential: true,
    examples: [
      {
        sentence_jp: '単純な方法が一番効果的だ。',
        sentence_ko: '단순한 방법이 가장 효과적이다.',
      },
    ],
  },
  {
    id: 103,
    kanji: '素直',
    reading: 'すなお',
    meaning_ko: '순수함, 솔직함',
    part_of_speech: 'na-adjective',
    category: '감정',
    frequency_rank: 103,
    is_essential: false,
    examples: [
      {
        sentence_jp: '彼はいつも素直な性格だ。',
        sentence_ko: '그는 언제나 순수한 성격이다.',
      },
    ],
  },
  {
    id: 104,
    kanji: '正直',
    reading: 'しょうじき',
    meaning_ko: '정직함',
    part_of_speech: 'na-adjective',
    category: '감정',
    frequency_rank: 104,
    is_essential: true,
    examples: [
      {
        sentence_jp: '正直に言えば、疲れている。',
        sentence_ko: '솔직히 말하면 피곤하다.',
      },
    ],
  },
  {
    id: 105,
    kanji: '真面目',
    reading: 'まじめ',
    meaning_ko: '성실함',
    part_of_speech: 'na-adjective',
    category: '감정',
    frequency_rank: 105,
    is_essential: true,
    examples: [
      {
        sentence_jp: '彼女はとても真面目な学生だ。',
        sentence_ko: '그녀는 아주 성실한 학생이다.',
      },
    ],
  },
  {
    id: 106,
    kanji: '厳しい',
    reading: 'きびしい',
    meaning_ko: '엄하다, 혹독하다',
    part_of_speech: 'i-adjective',
    category: '감정',
    frequency_rank: 106,
    is_essential: true,
    examples: [
      {
        sentence_jp: '父は昔から厳しい人だった。',
        sentence_ko: '아버지는 옛날부터 엄한 분이셨다.',
      },
    ],
  },
  {
    id: 107,
    kanji: '詳しい',
    reading: 'くわしい',
    meaning_ko: '자세하다, 정통하다',
    part_of_speech: 'i-adjective',
    category: '사고',
    frequency_rank: 107,
    is_essential: true,
    examples: [
      {
        sentence_jp: 'その件について詳しく教えてください。',
        sentence_ko: '그 건에 대해 자세히 알려 주세요.',
      },
    ],
  },
  {
    id: 108,
    kanji: '大人しい',
    reading: 'おとなしい',
    meaning_ko: '얌전하다, 온순하다',
    part_of_speech: 'i-adjective',
    category: '감정',
    frequency_rank: 108,
    is_essential: false,
    examples: [
      {
        sentence_jp: 'うちの犬はとても大人しい。',
        sentence_ko: '우리 개는 아주 얌전하다.',
      },
    ],
  },
  {
    id: 109,
    kanji: '面倒',
    reading: 'めんどう',
    meaning_ko: '귀찮음',
    part_of_speech: 'na-adjective',
    category: '감정',
    frequency_rank: 109,
    is_essential: true,
    examples: [
      {
        sentence_jp: '手続きが面倒で嫌になる。',
        sentence_ko: '절차가 귀찮아서 싫어진다.',
      },
    ],
  },
  {
    id: 110,
    kanji: '丁寧',
    reading: 'ていねい',
    meaning_ko: '정중함, 꼼꼼함',
    part_of_speech: 'na-adjective',
    category: '감정',
    frequency_rank: 110,
    is_essential: true,
    examples: [
      {
        sentence_jp: '彼は言葉遣いが丁寧だ。',
        sentence_ko: '그는 말투가 정중하다.',
      },
    ],
  },
  {
    id: 111,
    kanji: '簡単',
    reading: 'かんたん',
    meaning_ko: '간단함',
    part_of_speech: 'na-adjective',
    category: '사고',
    frequency_rank: 111,
    is_essential: true,
    examples: [
      {
        sentence_jp: '簡単に説明してもらえますか。',
        sentence_ko: '간단히 설명해 주시겠어요?',
      },
    ],
  },
  {
    id: 112,
    kanji: '自由',
    reading: 'じゆう',
    meaning_ko: '자유로움',
    part_of_speech: 'na-adjective',
    category: '사회',
    frequency_rank: 112,
    is_essential: true,
    examples: [
      {
        sentence_jp: '時間は自由に使ってください。',
        sentence_ko: '시간은 자유롭게 쓰세요.',
      },
    ],
  },
  {
    id: 113,
    kanji: '必要',
    reading: 'ひつよう',
    meaning_ko: '필요함',
    part_of_speech: 'na-adjective',
    category: '사고',
    frequency_rank: 113,
    is_essential: true,
    examples: [
      {
        sentence_jp: 'その書類は必要です。',
        sentence_ko: '그 서류는 필요합니다.',
      },
    ],
  },
  {
    id: 114,
    kanji: '十分',
    reading: 'じゅうぶん',
    meaning_ko: '충분함',
    part_of_speech: 'na-adjective',
    category: '사고',
    frequency_rank: 114,
    is_essential: true,
    examples: [
      {
        sentence_jp: 'もう十分休みました。',
        sentence_ko: '이미 충분히 쉬었어요.',
      },
    ],
  },
  {
    id: 115,
    kanji: '大切',
    reading: 'たいせつ',
    meaning_ko: '중요함, 소중함',
    part_of_speech: 'na-adjective',
    category: '사고',
    frequency_rank: 115,
    is_essential: true,
    examples: [
      {
        sentence_jp: '家族は一番大切です。',
        sentence_ko: '가족이 가장 소중합니다.',
      },
    ],
  },
  {
    id: 116,
    kanji: '偉い',
    reading: 'えらい',
    meaning_ko: '훌륭하다, 대단하다',
    part_of_speech: 'i-adjective',
    category: '감정',
    frequency_rank: 116,
    is_essential: false,
    examples: [
      {
        sentence_jp: '一人でやったの？偉いね。',
        sentence_ko: '혼자서 했어? 대단하네.',
      },
    ],
  },
  {
    id: 117,
    kanji: '恥ずかしい',
    reading: 'はずかしい',
    meaning_ko: '부끄럽다',
    part_of_speech: 'i-adjective',
    category: '감정',
    frequency_rank: 117,
    is_essential: true,
    examples: [
      {
        sentence_jp: 'みんなの前で話すのは恥ずかしい。',
        sentence_ko: '사람들 앞에서 말하는 건 부끄럽다.',
      },
    ],
  },
  {
    id: 118,
    kanji: '珍しい',
    reading: 'めずらしい',
    meaning_ko: '드물다, 진귀하다',
    part_of_speech: 'i-adjective',
    category: '사고',
    frequency_rank: 118,
    is_essential: true,
    examples: [
      {
        sentence_jp: 'そんなに早く来るなんて珍しいね。',
        sentence_ko: '그렇게 빨리 오다니 드문 일이네.',
      },
    ],
  },
  {
    id: 119,
    kanji: '懐かしい',
    reading: 'なつかしい',
    meaning_ko: '그립다',
    part_of_speech: 'i-adjective',
    category: '감정',
    frequency_rank: 119,
    is_essential: true,
    examples: [
      {
        sentence_jp: 'この曲を聞くと昔が懐かしい。',
        sentence_ko: '이 노래를 들으면 옛날이 그립다.',
      },
    ],
  },
  {
    id: 120,
    kanji: '嬉しい',
    reading: 'うれしい',
    meaning_ko: '기쁘다',
    part_of_speech: 'i-adjective',
    category: '감정',
    frequency_rank: 120,
    is_essential: true,
    examples: [
      {
        sentence_jp: 'プレゼントをもらって嬉しかった。',
        sentence_ko: '선물을 받아서 기뻤다.',
      },
    ],
  },
  {
    id: 121,
    kanji: '悲しい',
    reading: 'かなしい',
    meaning_ko: '슬프다',
    part_of_speech: 'i-adjective',
    category: '감정',
    frequency_rank: 121,
    is_essential: true,
    examples: [
      {
        sentence_jp: 'その映画はとても悲しい話だ。',
        sentence_ko: '그 영화는 아주 슬픈 이야기다.',
      },
    ],
  },
  {
    id: 122,
    kanji: '寂しい',
    reading: 'さびしい',
    meaning_ko: '외롭다, 쓸쓸하다',
    part_of_speech: 'i-adjective',
    category: '감정',
    frequency_rank: 122,
    is_essential: true,
    examples: [
      {
        sentence_jp: '一人で食べるのは寂しい。',
        sentence_ko: '혼자 먹는 건 외롭다.',
      },
    ],
  },
  {
    id: 123,
    kanji: '怖い',
    reading: 'こわい',
    meaning_ko: '무섭다',
    part_of_speech: 'i-adjective',
    category: '감정',
    frequency_rank: 123,
    is_essential: true,
    examples: [
      {
        sentence_jp: '夜道を歩くのは怖い。',
        sentence_ko: '밤길을 걷는 건 무섭다.',
      },
    ],
  },
  {
    id: 124,
    kanji: '強い',
    reading: 'つよい',
    meaning_ko: '강하다, 세다',
    part_of_speech: 'i-adjective',
    category: '감정',
    frequency_rank: 124,
    is_essential: true,
    examples: [
      {
        sentence_jp: '今日は風が強い。',
        sentence_ko: '오늘은 바람이 세다.',
      },
    ],
  },
  {
    id: 125,
    kanji: '弱い',
    reading: 'よわい',
    meaning_ko: '약하다',
    part_of_speech: 'i-adjective',
    category: '감정',
    frequency_rank: 125,
    is_essential: true,
    examples: [
      {
        sentence_jp: 'お酒に弱いので少ししか飲まない。',
        sentence_ko: '술이 약해서 조금밖에 마시지 않아.',
      },
    ],
  },
  {
    id: 126,
    kanji: '深い',
    reading: 'ふかい',
    meaning_ko: '깊다',
    part_of_speech: 'i-adjective',
    category: '자연',
    frequency_rank: 126,
    is_essential: true,
    examples: [
      {
        sentence_jp: 'この川はとても深い。',
        sentence_ko: '이 강은 아주 깊다.',
      },
    ],
  },
  {
    id: 127,
    kanji: '浅い',
    reading: 'あさい',
    meaning_ko: '얕다',
    part_of_speech: 'i-adjective',
    category: '자연',
    frequency_rank: 127,
    is_essential: false,
    examples: [
      {
        sentence_jp: 'この池は浅いので安全だ。',
        sentence_ko: '이 연못은 얕아서 안전하다.',
      },
    ],
  },
  {
    id: 128,
    kanji: '厚い',
    reading: 'あつい',
    meaning_ko: '두껍다',
    part_of_speech: 'i-adjective',
    category: '사물',
    frequency_rank: 128,
    is_essential: true,
    examples: [
      {
        sentence_jp: 'この本はとても厚い。',
        sentence_ko: '이 책은 아주 두껍다.',
      },
    ],
  },
  {
    id: 129,
    kanji: '薄い',
    reading: 'うすい',
    meaning_ko: '얇다, 연하다',
    part_of_speech: 'i-adjective',
    category: '사물',
    frequency_rank: 129,
    is_essential: true,
    examples: [
      {
        sentence_jp: 'コーヒーが薄すぎる。',
        sentence_ko: '커피가 너무 연하다.',
      },
    ],
  },
  {
    id: 130,
    kanji: '硬い',
    reading: 'かたい',
    meaning_ko: '단단하다, 딱딱하다',
    part_of_speech: 'i-adjective',
    category: '사물',
    frequency_rank: 130,
    is_essential: true,
    examples: [
      {
        sentence_jp: 'このパンは硬くなっている。',
        sentence_ko: '이 빵은 딱딱해져 있다.',
      },
    ],
  },

  // ==================== 부사 ====================
  {
    id: 131,
    kanji: null,
    reading: 'やっと',
    meaning_ko: '드디어, 간신히',
    part_of_speech: 'adverb',
    category: '시간',
    frequency_rank: 131,
    is_essential: true,
    examples: [
      {
        sentence_jp: 'やっと試験が終わった。',
        sentence_ko: '드디어 시험이 끝났다.',
      },
    ],
  },
  {
    id: 132,
    kanji: null,
    reading: 'きっと',
    meaning_ko: '반드시, 분명히',
    part_of_speech: 'adverb',
    category: '사고',
    frequency_rank: 132,
    is_essential: true,
    examples: [
      {
        sentence_jp: '彼はきっと来ると思う。',
        sentence_ko: '그는 분명히 올 거라고 생각해.',
      },
    ],
  },
  {
    id: 133,
    kanji: null,
    reading: 'さっそく',
    meaning_ko: '즉시, 곧장',
    part_of_speech: 'adverb',
    category: '시간',
    frequency_rank: 133,
    is_essential: true,
    examples: [
      {
        sentence_jp: 'さっそく仕事に取りかかった。',
        sentence_ko: '곧장 일에 착수했다.',
      },
    ],
  },
  {
    id: 134,
    kanji: null,
    reading: 'たぶん',
    meaning_ko: '아마도',
    part_of_speech: 'adverb',
    category: '사고',
    frequency_rank: 134,
    is_essential: true,
    examples: [
      {
        sentence_jp: 'たぶん明日は雨だろう。',
        sentence_ko: '아마 내일은 비가 올 것이다.',
      },
    ],
  },
  {
    id: 135,
    kanji: '急に',
    reading: 'きゅうに',
    meaning_ko: '갑자기',
    part_of_speech: 'adverb',
    category: '시간',
    frequency_rank: 135,
    is_essential: true,
    examples: [
      {
        sentence_jp: '急に雨が降ってきた。',
        sentence_ko: '갑자기 비가 내리기 시작했다.',
      },
    ],
  },
  {
    id: 136,
    kanji: '突然',
    reading: 'とつぜん',
    meaning_ko: '돌연, 갑자기',
    part_of_speech: 'adverb',
    category: '시간',
    frequency_rank: 136,
    is_essential: true,
    examples: [
      {
        sentence_jp: '突然、電気が消えた。',
        sentence_ko: '돌연 전기가 나갔다.',
      },
    ],
  },
  {
    id: 137,
    kanji: null,
    reading: 'もちろん',
    meaning_ko: '물론',
    part_of_speech: 'adverb',
    category: '사고',
    frequency_rank: 137,
    is_essential: true,
    examples: [
      {
        sentence_jp: 'もちろん手伝いますよ。',
        sentence_ko: '물론 도와드릴게요.',
      },
    ],
  },
  {
    id: 138,
    kanji: null,
    reading: 'そのうち',
    meaning_ko: '머지않아, 곧',
    part_of_speech: 'adverb',
    category: '시간',
    frequency_rank: 138,
    is_essential: false,
    examples: [
      {
        sentence_jp: 'そのうちまた会いましょう。',
        sentence_ko: '머지않아 또 만나요.',
      },
    ],
  },
  {
    id: 139,
    kanji: null,
    reading: 'ついでに',
    meaning_ko: '하는 김에',
    part_of_speech: 'adverb',
    category: '시간',
    frequency_rank: 139,
    is_essential: true,
    examples: [
      {
        sentence_jp: '買い物のついでに郵便局に寄った。',
        sentence_ko: '쇼핑하는 김에 우체국에 들렀다.',
      },
    ],
  },
  {
    id: 140,
    kanji: null,
    reading: 'しばらく',
    meaning_ko: '잠시, 당분간',
    part_of_speech: 'adverb',
    category: '시간',
    frequency_rank: 140,
    is_essential: true,
    examples: [
      {
        sentence_jp: 'しばらくお待ちください。',
        sentence_ko: '잠시만 기다려 주세요.',
      },
    ],
  },
  {
    id: 141,
    kanji: null,
    reading: 'ほとんど',
    meaning_ko: '거의',
    part_of_speech: 'adverb',
    category: '사고',
    frequency_rank: 141,
    is_essential: true,
    examples: [
      {
        sentence_jp: 'ほとんどの人が賛成した。',
        sentence_ko: '거의 모든 사람이 찬성했다.',
      },
    ],
  },
  {
    id: 142,
    kanji: null,
    reading: 'ずっと',
    meaning_ko: '쭉, 계속',
    part_of_speech: 'adverb',
    category: '시간',
    frequency_rank: 142,
    is_essential: true,
    examples: [
      {
        sentence_jp: '朝からずっと勉強している。',
        sentence_ko: '아침부터 계속 공부하고 있다.',
      },
    ],
  },
  {
    id: 143,
    kanji: null,
    reading: 'なるべく',
    meaning_ko: '가능한 한',
    part_of_speech: 'adverb',
    category: '사고',
    frequency_rank: 143,
    is_essential: true,
    examples: [
      {
        sentence_jp: 'なるべく早く来てください。',
        sentence_ko: '가능한 한 빨리 와 주세요.',
      },
    ],
  },
  {
    id: 144,
    kanji: null,
    reading: 'たまに',
    meaning_ko: '가끔',
    part_of_speech: 'adverb',
    category: '시간',
    frequency_rank: 144,
    is_essential: true,
    examples: [
      {
        sentence_jp: 'たまに映画を見に行く。',
        sentence_ko: '가끔 영화를 보러 간다.',
      },
    ],
  },
  {
    id: 145,
    kanji: null,
    reading: 'わざわざ',
    meaning_ko: '일부러',
    part_of_speech: 'adverb',
    category: '감정',
    frequency_rank: 145,
    is_essential: false,
    examples: [
      {
        sentence_jp: 'わざわざ来てくれてありがとう。',
        sentence_ko: '일부러 와 줘서 고마워.',
      },
    ],
  },

  // ==================== 추가 동사 ====================
  {
    id: 146,
    kanji: '申し込む',
    reading: 'もうしこむ',
    meaning_ko: '신청하다',
    part_of_speech: 'verb',
    category: '업무',
    frequency_rank: 146,
    is_essential: true,
    examples: [
      {
        sentence_jp: 'セミナーに申し込みました。',
        sentence_ko: '세미나에 신청했어요.',
      },
    ],
  },
  {
    id: 147,
    kanji: '支払う',
    reading: 'しはらう',
    meaning_ko: '지불하다',
    part_of_speech: 'verb',
    category: '업무',
    frequency_rank: 147,
    is_essential: true,
    examples: [
      {
        sentence_jp: 'カードで支払います。',
        sentence_ko: '카드로 결제합니다.',
      },
    ],
  },
  {
    id: 148,
    kanji: '比較する',
    reading: 'ひかくする',
    meaning_ko: '비교하다',
    part_of_speech: 'verb',
    category: '사고',
    frequency_rank: 148,
    is_essential: false,
    examples: [
      {
        sentence_jp: '二つの製品を比較した。',
        sentence_ko: '두 제품을 비교했다.',
      },
    ],
  },
  {
    id: 149,
    kanji: '調べる',
    reading: 'しらべる',
    meaning_ko: '조사하다, 찾아보다',
    part_of_speech: 'verb',
    category: '사고',
    frequency_rank: 149,
    is_essential: true,
    examples: [
      {
        sentence_jp: '辞書で意味を調べた。',
        sentence_ko: '사전에서 뜻을 찾아봤다.',
      },
    ],
  },
  {
    id: 150,
    kanji: '感じる',
    reading: 'かんじる',
    meaning_ko: '느끼다',
    part_of_speech: 'verb',
    category: '감정',
    frequency_rank: 150,
    is_essential: true,
    examples: [
      {
        sentence_jp: '何か冷たい風を感じた。',
        sentence_ko: '뭔가 차가운 바람을 느꼈다.',
      },
    ],
  },
  {
    id: 151,
    kanji: '信じる',
    reading: 'しんじる',
    meaning_ko: '믿다',
    part_of_speech: 'verb',
    category: '감정',
    frequency_rank: 151,
    is_essential: true,
    examples: [
      {
        sentence_jp: '彼の言葉を信じたい。',
        sentence_ko: '그의 말을 믿고 싶다.',
      },
    ],
  },
  {
    id: 152,
    kanji: '怒る',
    reading: 'おこる',
    meaning_ko: '화내다',
    part_of_speech: 'verb',
    category: '감정',
    frequency_rank: 152,
    is_essential: true,
    examples: [
      {
        sentence_jp: '母が珍しく怒っている。',
        sentence_ko: '어머니가 드물게 화를 내고 있다.',
      },
    ],
  },
  {
    id: 153,
    kanji: '喜ぶ',
    reading: 'よろこぶ',
    meaning_ko: '기뻐하다',
    part_of_speech: 'verb',
    category: '감정',
    frequency_rank: 153,
    is_essential: true,
    examples: [
      {
        sentence_jp: '合格の知らせに家族全員が喜んだ。',
        sentence_ko: '합격 소식에 가족 모두가 기뻐했다.',
      },
    ],
  },
  {
    id: 154,
    kanji: '冷える',
    reading: 'ひえる',
    meaning_ko: '차가워지다, 식다',
    part_of_speech: 'verb',
    category: '자연',
    frequency_rank: 154,
    is_essential: false,
    examples: [
      {
        sentence_jp: '夜は急に冷える。',
        sentence_ko: '밤에는 갑자기 차가워진다.',
      },
    ],
  },
  {
    id: 155,
    kanji: '温める',
    reading: 'あたためる',
    meaning_ko: '데우다',
    part_of_speech: 'verb',
    category: '일상',
    frequency_rank: 155,
    is_essential: false,
    examples: [
      {
        sentence_jp: '電子レンジでお弁当を温めた。',
        sentence_ko: '전자레인지로 도시락을 데웠다.',
      },
    ],
  },
  {
    id: 156,
    kanji: '沸く',
    reading: 'わく',
    meaning_ko: '끓다',
    part_of_speech: 'verb',
    category: '일상',
    frequency_rank: 156,
    is_essential: false,
    examples: [
      {
        sentence_jp: 'お湯が沸きました。',
        sentence_ko: '물이 끓었어요.',
      },
    ],
  },
  {
    id: 157,
    kanji: '乾く',
    reading: 'かわく',
    meaning_ko: '마르다',
    part_of_speech: 'verb',
    category: '자연',
    frequency_rank: 157,
    is_essential: true,
    examples: [
      {
        sentence_jp: '洗濯物がすぐに乾いた。',
        sentence_ko: '빨래가 금방 말랐다.',
      },
    ],
  },
  {
    id: 158,
    kanji: '混む',
    reading: 'こむ',
    meaning_ko: '붐비다',
    part_of_speech: 'verb',
    category: '일상',
    frequency_rank: 158,
    is_essential: true,
    examples: [
      {
        sentence_jp: '週末は電車がとても混む。',
        sentence_ko: '주말에는 전철이 아주 붐빈다.',
      },
    ],
  },
  {
    id: 159,
    kanji: '動く',
    reading: 'うごく',
    meaning_ko: '움직이다',
    part_of_speech: 'verb',
    category: '일상',
    frequency_rank: 159,
    is_essential: true,
    examples: [
      {
        sentence_jp: 'この時計は古いのにまだ動く。',
        sentence_ko: '이 시계는 오래됐는데도 아직 움직인다.',
      },
    ],
  },
  {
    id: 160,
    kanji: '動かす',
    reading: 'うごかす',
    meaning_ko: '움직이게 하다',
    part_of_speech: 'verb',
    category: '일상',
    frequency_rank: 160,
    is_essential: false,
    examples: [
      {
        sentence_jp: '机を少し動かしてください。',
        sentence_ko: '책상을 조금 옮겨 주세요.',
      },
    ],
  },
  {
    id: 161,
    kanji: '調査する',
    reading: 'ちょうさする',
    meaning_ko: '조사하다',
    part_of_speech: 'verb',
    category: '업무',
    frequency_rank: 161,
    is_essential: false,
    examples: [
      {
        sentence_jp: '市場を調査する必要がある。',
        sentence_ko: '시장을 조사할 필요가 있다.',
      },
    ],
  },
  {
    id: 162,
    kanji: '参加する',
    reading: 'さんかする',
    meaning_ko: '참가하다',
    part_of_speech: 'verb',
    category: '업무',
    frequency_rank: 162,
    is_essential: true,
    examples: [
      {
        sentence_jp: '会議に参加します。',
        sentence_ko: '회의에 참가합니다.',
      },
    ],
  },
  {
    id: 163,
    kanji: '出席する',
    reading: 'しゅっせきする',
    meaning_ko: '출석하다',
    part_of_speech: 'verb',
    category: '학업',
    frequency_rank: 163,
    is_essential: true,
    examples: [
      {
        sentence_jp: '今日の授業に出席できません。',
        sentence_ko: '오늘 수업에 출석할 수 없어요.',
      },
    ],
  },
  {
    id: 164,
    kanji: '成長する',
    reading: 'せいちょうする',
    meaning_ko: '성장하다',
    part_of_speech: 'verb',
    category: '변화',
    frequency_rank: 164,
    is_essential: true,
    examples: [
      {
        sentence_jp: '子供はあっという間に成長する。',
        sentence_ko: '아이는 눈 깜짝할 새 성장한다.',
      },
    ],
  },
  {
    id: 165,
    kanji: '発達する',
    reading: 'はったつする',
    meaning_ko: '발달하다',
    part_of_speech: 'verb',
    category: '사회',
    frequency_rank: 165,
    is_essential: false,
    examples: [
      {
        sentence_jp: '技術がどんどん発達している。',
        sentence_ko: '기술이 점점 발달하고 있다.',
      },
    ],
  },
  {
    id: 166,
    kanji: '利用する',
    reading: 'りようする',
    meaning_ko: '이용하다',
    part_of_speech: 'verb',
    category: '일상',
    frequency_rank: 166,
    is_essential: true,
    examples: [
      {
        sentence_jp: '毎日バスを利用している。',
        sentence_ko: '매일 버스를 이용하고 있다.',
      },
    ],
  },
  {
    id: 167,
    kanji: '使用する',
    reading: 'しようする',
    meaning_ko: '사용하다',
    part_of_speech: 'verb',
    category: '업무',
    frequency_rank: 167,
    is_essential: true,
    examples: [
      {
        sentence_jp: 'この道具はどう使用しますか。',
        sentence_ko: '이 도구는 어떻게 사용합니까?',
      },
    ],
  },
  {
    id: 168,
    kanji: '注意する',
    reading: 'ちゅういする',
    meaning_ko: '주의하다',
    part_of_speech: 'verb',
    category: '일상',
    frequency_rank: 168,
    is_essential: true,
    examples: [
      {
        sentence_jp: '車に注意してください。',
        sentence_ko: '차를 조심하세요.',
      },
    ],
  },
  {
    id: 169,
    kanji: '心配する',
    reading: 'しんぱいする',
    meaning_ko: '걱정하다',
    part_of_speech: 'verb',
    category: '감정',
    frequency_rank: 169,
    is_essential: true,
    examples: [
      {
        sentence_jp: '母の健康を心配している。',
        sentence_ko: '어머니의 건강을 걱정하고 있다.',
      },
    ],
  },
  {
    id: 170,
    kanji: '安心する',
    reading: 'あんしんする',
    meaning_ko: '안심하다',
    part_of_speech: 'verb',
    category: '감정',
    frequency_rank: 170,
    is_essential: true,
    examples: [
      {
        sentence_jp: '無事と聞いて安心した。',
        sentence_ko: '무사하다는 말을 듣고 안심했다.',
      },
    ],
  },
  {
    id: 171,
    kanji: '緊張する',
    reading: 'きんちょうする',
    meaning_ko: '긴장하다',
    part_of_speech: 'verb',
    category: '감정',
    frequency_rank: 171,
    is_essential: true,
    examples: [
      {
        sentence_jp: '発表の前はいつも緊張する。',
        sentence_ko: '발표 전에는 늘 긴장한다.',
      },
    ],
  },
  {
    id: 172,
    kanji: '我慢する',
    reading: 'がまんする',
    meaning_ko: '참다',
    part_of_speech: 'verb',
    category: '감정',
    frequency_rank: 172,
    is_essential: true,
    examples: [
      {
        sentence_jp: '眠いけど、我慢して勉強している。',
        sentence_ko: '졸리지만 참으면서 공부하고 있다.',
      },
    ],
  },
  {
    id: 173,
    kanji: '後悔する',
    reading: 'こうかいする',
    meaning_ko: '후회하다',
    part_of_speech: 'verb',
    category: '감정',
    frequency_rank: 173,
    is_essential: false,
    examples: [
      {
        sentence_jp: '今になって後悔している。',
        sentence_ko: '이제 와서 후회하고 있다.',
      },
    ],
  },
  {
    id: 174,
    kanji: '感動する',
    reading: 'かんどうする',
    meaning_ko: '감동하다',
    part_of_speech: 'verb',
    category: '감정',
    frequency_rank: 174,
    is_essential: true,
    examples: [
      {
        sentence_jp: 'その映画に本当に感動した。',
        sentence_ko: '그 영화에 정말 감동했다.',
      },
    ],
  },
  {
    id: 175,
    kanji: '反対する',
    reading: 'はんたいする',
    meaning_ko: '반대하다',
    part_of_speech: 'verb',
    category: '사고',
    frequency_rank: 175,
    is_essential: true,
    examples: [
      {
        sentence_jp: 'その案に反対する人が多い。',
        sentence_ko: '그 안에 반대하는 사람이 많다.',
      },
    ],
  },
  {
    id: 176,
    kanji: '賛成する',
    reading: 'さんせいする',
    meaning_ko: '찬성하다',
    part_of_speech: 'verb',
    category: '사고',
    frequency_rank: 176,
    is_essential: true,
    examples: [
      {
        sentence_jp: '私はあなたの意見に賛成する。',
        sentence_ko: '나는 당신 의견에 찬성한다.',
      },
    ],
  },
  {
    id: 177,
    kanji: '説得する',
    reading: 'せっとくする',
    meaning_ko: '설득하다',
    part_of_speech: 'verb',
    category: '관계',
    frequency_rank: 177,
    is_essential: false,
    examples: [
      {
        sentence_jp: '彼を説得するのは難しい。',
        sentence_ko: '그를 설득하는 건 어렵다.',
      },
    ],
  },
  {
    id: 178,
    kanji: '協力する',
    reading: 'きょうりょくする',
    meaning_ko: '협력하다',
    part_of_speech: 'verb',
    category: '업무',
    frequency_rank: 178,
    is_essential: true,
    examples: [
      {
        sentence_jp: '皆で協力して準備した。',
        sentence_ko: '다 같이 협력해서 준비했다.',
      },
    ],
  },
  {
    id: 179,
    kanji: '努力する',
    reading: 'どりょくする',
    meaning_ko: '노력하다',
    part_of_speech: 'verb',
    category: '학업',
    frequency_rank: 179,
    is_essential: true,
    examples: [
      {
        sentence_jp: '毎日努力すれば必ず上達する。',
        sentence_ko: '매일 노력하면 반드시 실력이 는다.',
      },
    ],
  },
  {
    id: 180,
    kanji: '成功する',
    reading: 'せいこうする',
    meaning_ko: '성공하다',
    part_of_speech: 'verb',
    category: '업무',
    frequency_rank: 180,
    is_essential: true,
    examples: [
      {
        sentence_jp: '実験はようやく成功した。',
        sentence_ko: '실험은 마침내 성공했다.',
      },
    ],
  },

  // ==================== 추가 명사 ====================
  {
    id: 181,
    kanji: '交流',
    reading: 'こうりゅう',
    meaning_ko: '교류',
    part_of_speech: 'noun',
    category: '사회',
    frequency_rank: 181,
    is_essential: false,
    examples: [
      {
        sentence_jp: '国際交流のイベントに参加した。',
        sentence_ko: '국제 교류 행사에 참가했다.',
      },
    ],
  },
  {
    id: 182,
    kanji: '健康',
    reading: 'けんこう',
    meaning_ko: '건강',
    part_of_speech: 'noun',
    category: '건강',
    frequency_rank: 182,
    is_essential: true,
    examples: [
      {
        sentence_jp: '健康のために運動している。',
        sentence_ko: '건강을 위해 운동하고 있다.',
      },
    ],
  },
  {
    id: 183,
    kanji: '病気',
    reading: 'びょうき',
    meaning_ko: '병',
    part_of_speech: 'noun',
    category: '건강',
    frequency_rank: 183,
    is_essential: true,
    examples: [
      {
        sentence_jp: '祖母は重い病気にかかった。',
        sentence_ko: '할머니는 큰 병에 걸리셨다.',
      },
    ],
  },
  {
    id: 184,
    kanji: '薬',
    reading: 'くすり',
    meaning_ko: '약',
    part_of_speech: 'noun',
    category: '건강',
    frequency_rank: 184,
    is_essential: true,
    examples: [
      {
        sentence_jp: '食後に薬を飲みます。',
        sentence_ko: '식후에 약을 먹어요.',
      },
    ],
  },
  {
    id: 185,
    kanji: '病院',
    reading: 'びょういん',
    meaning_ko: '병원',
    part_of_speech: 'noun',
    category: '건강',
    frequency_rank: 185,
    is_essential: true,
    examples: [
      {
        sentence_jp: '朝から病院に行ってきた。',
        sentence_ko: '아침부터 병원에 다녀왔다.',
      },
    ],
  },
  {
    id: 186,
    kanji: '医者',
    reading: 'いしゃ',
    meaning_ko: '의사',
    part_of_speech: 'noun',
    category: '건강',
    frequency_rank: 186,
    is_essential: true,
    examples: [
      {
        sentence_jp: '兄は医者になりたがっている。',
        sentence_ko: '형은 의사가 되고 싶어 한다.',
      },
    ],
  },
  {
    id: 187,
    kanji: '食事',
    reading: 'しょくじ',
    meaning_ko: '식사',
    part_of_speech: 'noun',
    category: '일상',
    frequency_rank: 187,
    is_essential: true,
    examples: [
      {
        sentence_jp: '毎日三食きちんと食事をする。',
        sentence_ko: '매일 세 끼 제대로 식사한다.',
      },
    ],
  },
  {
    id: 188,
    kanji: '注文',
    reading: 'ちゅうもん',
    meaning_ko: '주문',
    part_of_speech: 'noun',
    category: '일상',
    frequency_rank: 188,
    is_essential: true,
    examples: [
      {
        sentence_jp: '注文はもうお決まりですか。',
        sentence_ko: '주문은 정하셨나요?',
      },
    ],
  },
  {
    id: 189,
    kanji: '値段',
    reading: 'ねだん',
    meaning_ko: '가격',
    part_of_speech: 'noun',
    category: '일상',
    frequency_rank: 189,
    is_essential: true,
    examples: [
      {
        sentence_jp: 'この服は値段が高い。',
        sentence_ko: '이 옷은 가격이 비싸다.',
      },
    ],
  },
  {
    id: 190,
    kanji: '財布',
    reading: 'さいふ',
    meaning_ko: '지갑',
    part_of_speech: 'noun',
    category: '일상',
    frequency_rank: 190,
    is_essential: true,
    examples: [
      {
        sentence_jp: '駅で財布をなくした。',
        sentence_ko: '역에서 지갑을 잃어버렸다.',
      },
    ],
  },
  {
    id: 191,
    kanji: '電車',
    reading: 'でんしゃ',
    meaning_ko: '전철',
    part_of_speech: 'noun',
    category: '이동',
    frequency_rank: 191,
    is_essential: true,
    examples: [
      {
        sentence_jp: '朝の電車はいつも混んでいる。',
        sentence_ko: '아침 전철은 항상 붐빈다.',
      },
    ],
  },
  {
    id: 192,
    kanji: '席',
    reading: 'せき',
    meaning_ko: '자리, 좌석',
    part_of_speech: 'noun',
    category: '일상',
    frequency_rank: 192,
    is_essential: true,
    examples: [
      {
        sentence_jp: '窓側の席が好きです。',
        sentence_ko: '창가 쪽 자리를 좋아해요.',
      },
    ],
  },
  {
    id: 193,
    kanji: '切符',
    reading: 'きっぷ',
    meaning_ko: '표, 티켓',
    part_of_speech: 'noun',
    category: '이동',
    frequency_rank: 193,
    is_essential: true,
    examples: [
      {
        sentence_jp: '新幹線の切符を買った。',
        sentence_ko: '신칸센 표를 샀다.',
      },
    ],
  },
  {
    id: 194,
    kanji: '周り',
    reading: 'まわり',
    meaning_ko: '주위, 주변',
    part_of_speech: 'noun',
    category: '장소',
    frequency_rank: 194,
    is_essential: true,
    examples: [
      {
        sentence_jp: '家の周りを散歩した。',
        sentence_ko: '집 주변을 산책했다.',
      },
    ],
  },
  {
    id: 195,
    kanji: '両方',
    reading: 'りょうほう',
    meaning_ko: '양쪽',
    part_of_speech: 'noun',
    category: '사고',
    frequency_rank: 195,
    is_essential: true,
    examples: [
      {
        sentence_jp: '両方の意見を聞きたい。',
        sentence_ko: '양쪽 의견을 듣고 싶다.',
      },
    ],
  },
  {
    id: 196,
    kanji: '途中',
    reading: 'とちゅう',
    meaning_ko: '도중',
    part_of_speech: 'noun',
    category: '시간',
    frequency_rank: 196,
    is_essential: true,
    examples: [
      {
        sentence_jp: '家に帰る途中で雨が降り出した。',
        sentence_ko: '집에 가는 도중에 비가 내리기 시작했다.',
      },
    ],
  },
  {
    id: 197,
    kanji: '最中',
    reading: 'さいちゅう',
    meaning_ko: '한창 ~중',
    part_of_speech: 'noun',
    category: '시간',
    frequency_rank: 197,
    is_essential: false,
    examples: [
      {
        sentence_jp: '会議の最中に電話が鳴った。',
        sentence_ko: '회의 한창 중에 전화가 울렸다.',
      },
    ],
  },
  {
    id: 198,
    kanji: '自身',
    reading: 'じしん',
    meaning_ko: '자신, 본인',
    part_of_speech: 'noun',
    category: '관계',
    frequency_rank: 198,
    is_essential: false,
    examples: [
      {
        sentence_jp: '自分自身をもっと信じよう。',
        sentence_ko: '자기 자신을 더 믿자.',
      },
    ],
  },
  {
    id: 199,
    kanji: '自信',
    reading: 'じしん',
    meaning_ko: '자신, 자신감',
    part_of_speech: 'noun',
    category: '감정',
    frequency_rank: 199,
    is_essential: true,
    examples: [
      {
        sentence_jp: '試験に自信がある。',
        sentence_ko: '시험에 자신이 있다.',
      },
    ],
  },
  {
    id: 200,
    kanji: '能力',
    reading: 'のうりょく',
    meaning_ko: '능력',
    part_of_speech: 'noun',
    category: '업무',
    frequency_rank: 200,
    is_essential: true,
    examples: [
      {
        sentence_jp: '彼の能力はとても高い。',
        sentence_ko: '그의 능력은 아주 뛰어나다.',
      },
    ],
  },
  {
    id: 201,
    kanji: '努力',
    reading: 'どりょく',
    meaning_ko: '노력',
    part_of_speech: 'noun',
    category: '학업',
    frequency_rank: 201,
    is_essential: false,
    examples: [
      {
        sentence_jp: '彼の努力には頭が下がる。',
        sentence_ko: '그의 노력에는 고개가 숙여진다.',
      },
    ],
  },
  {
    id: 202,
    kanji: '技術',
    reading: 'ぎじゅつ',
    meaning_ko: '기술',
    part_of_speech: 'noun',
    category: '사회',
    frequency_rank: 202,
    is_essential: true,
    examples: [
      {
        sentence_jp: '最新技術を学びたい。',
        sentence_ko: '최신 기술을 배우고 싶다.',
      },
    ],
  },
  {
    id: 203,
    kanji: '研究',
    reading: 'けんきゅう',
    meaning_ko: '연구',
    part_of_speech: 'noun',
    category: '학업',
    frequency_rank: 203,
    is_essential: true,
    examples: [
      {
        sentence_jp: '言語の研究を続けている。',
        sentence_ko: '언어 연구를 계속하고 있다.',
      },
    ],
  },
  {
    id: 204,
    kanji: '科学',
    reading: 'かがく',
    meaning_ko: '과학',
    part_of_speech: 'noun',
    category: '학업',
    frequency_rank: 204,
    is_essential: true,
    examples: [
      {
        sentence_jp: '科学の発展は目覚ましい。',
        sentence_ko: '과학의 발전은 눈부시다.',
      },
    ],
  },
  {
    id: 205,
    kanji: '歴史',
    reading: 'れきし',
    meaning_ko: '역사',
    part_of_speech: 'noun',
    category: '학업',
    frequency_rank: 205,
    is_essential: true,
    examples: [
      {
        sentence_jp: '日本の歴史に興味がある。',
        sentence_ko: '일본 역사에 흥미가 있다.',
      },
    ],
  },
  {
    id: 206,
    kanji: '宗教',
    reading: 'しゅうきょう',
    meaning_ko: '종교',
    part_of_speech: 'noun',
    category: '사회',
    frequency_rank: 206,
    is_essential: false,
    examples: [
      {
        sentence_jp: '彼は宗教を持っていない。',
        sentence_ko: '그는 종교를 가지고 있지 않다.',
      },
    ],
  },
  {
    id: 207,
    kanji: '意志',
    reading: 'いし',
    meaning_ko: '의지',
    part_of_speech: 'noun',
    category: '감정',
    frequency_rank: 207,
    is_essential: false,
    examples: [
      {
        sentence_jp: '強い意志を持っている。',
        sentence_ko: '강한 의지를 가지고 있다.',
      },
    ],
  },
  {
    id: 208,
    kanji: '感情',
    reading: 'かんじょう',
    meaning_ko: '감정',
    part_of_speech: 'noun',
    category: '감정',
    frequency_rank: 208,
    is_essential: true,
    examples: [
      {
        sentence_jp: '感情を素直に表す。',
        sentence_ko: '감정을 솔직하게 표현한다.',
      },
    ],
  },
  {
    id: 209,
    kanji: '夢',
    reading: 'ゆめ',
    meaning_ko: '꿈',
    part_of_speech: 'noun',
    category: '감정',
    frequency_rank: 209,
    is_essential: true,
    examples: [
      {
        sentence_jp: '夢を叶えるために努力する。',
        sentence_ko: '꿈을 이루기 위해 노력한다.',
      },
    ],
  },
  {
    id: 210,
    kanji: '希望',
    reading: 'きぼう',
    meaning_ko: '희망',
    part_of_speech: 'noun',
    category: '감정',
    frequency_rank: 210,
    is_essential: true,
    examples: [
      {
        sentence_jp: 'いつも希望を持って生きたい。',
        sentence_ko: '늘 희망을 가지고 살고 싶다.',
      },
    ],
  },

  // ==================== 추가 형용사 & 부사 ====================
  {
    id: 211,
    kanji: '豊か',
    reading: 'ゆたか',
    meaning_ko: '풍부함, 풍요로움',
    part_of_speech: 'na-adjective',
    category: '감정',
    frequency_rank: 211,
    is_essential: true,
    examples: [
      {
        sentence_jp: '心が豊かになる本だ。',
        sentence_ko: '마음이 풍요로워지는 책이다.',
      },
    ],
  },
  {
    id: 212,
    kanji: '静か',
    reading: 'しずか',
    meaning_ko: '조용함',
    part_of_speech: 'na-adjective',
    category: '감정',
    frequency_rank: 212,
    is_essential: true,
    examples: [
      {
        sentence_jp: 'ここは静かで集中できる。',
        sentence_ko: '여기는 조용해서 집중이 된다.',
      },
    ],
  },
  {
    id: 213,
    kanji: 'にぎやか',
    reading: 'にぎやか',
    meaning_ko: '번화함, 시끌벅적함',
    part_of_speech: 'na-adjective',
    category: '감정',
    frequency_rank: 213,
    is_essential: true,
    examples: [
      {
        sentence_jp: '週末の商店街はにぎやかだ。',
        sentence_ko: '주말 상점가는 시끌벅적하다.',
      },
    ],
  },
  {
    id: 214,
    kanji: '正しい',
    reading: 'ただしい',
    meaning_ko: '올바르다, 옳다',
    part_of_speech: 'i-adjective',
    category: '사고',
    frequency_rank: 214,
    is_essential: true,
    examples: [
      {
        sentence_jp: '正しい答えを選んでください。',
        sentence_ko: '올바른 답을 고르세요.',
      },
    ],
  },
  {
    id: 215,
    kanji: '親しい',
    reading: 'したしい',
    meaning_ko: '친하다',
    part_of_speech: 'i-adjective',
    category: '관계',
    frequency_rank: 215,
    is_essential: false,
    examples: [
      {
        sentence_jp: '中学からの親しい友達だ。',
        sentence_ko: '중학교 때부터 친한 친구다.',
      },
    ],
  },
  {
    id: 216,
    kanji: '優しい',
    reading: 'やさしい',
    meaning_ko: '상냥하다, 다정하다',
    part_of_speech: 'i-adjective',
    category: '감정',
    frequency_rank: 216,
    is_essential: true,
    examples: [
      {
        sentence_jp: '彼はいつも優しい。',
        sentence_ko: '그는 언제나 다정하다.',
      },
    ],
  },
  {
    id: 217,
    kanji: null,
    reading: 'ぜひ',
    meaning_ko: '꼭, 반드시',
    part_of_speech: 'adverb',
    category: '사고',
    frequency_rank: 217,
    is_essential: true,
    examples: [
      {
        sentence_jp: 'ぜひ一度来てください。',
        sentence_ko: '꼭 한번 와 주세요.',
      },
    ],
  },
  {
    id: 218,
    kanji: null,
    reading: 'なかなか',
    meaning_ko: '좀처럼, 꽤',
    part_of_speech: 'adverb',
    category: '사고',
    frequency_rank: 218,
    is_essential: true,
    examples: [
      {
        sentence_jp: 'なかなか上手に書けている。',
        sentence_ko: '꽤 잘 써졌다.',
      },
    ],
  },
  {
    id: 219,
    kanji: null,
    reading: 'やはり',
    meaning_ko: '역시',
    part_of_speech: 'adverb',
    category: '사고',
    frequency_rank: 219,
    is_essential: true,
    examples: [
      {
        sentence_jp: 'やはり彼の考えが正しかった。',
        sentence_ko: '역시 그의 생각이 옳았다.',
      },
    ],
  },
  {
    id: 220,
    kanji: null,
    reading: 'そろそろ',
    meaning_ko: '슬슬',
    part_of_speech: 'adverb',
    category: '시간',
    frequency_rank: 220,
    is_essential: true,
    examples: [
      {
        sentence_jp: 'そろそろ帰りましょう。',
        sentence_ko: '슬슬 돌아갑시다.',
      },
    ],
  },
];

export const CATEGORIES = Array.from(new Set(SEED_WORDS.map((w) => w.category))).sort();

export const TOTAL_SEED_WORDS = SEED_WORDS.length;
